### PR TITLE
Implement weekday and date support

### PR DESCRIPTION
**Pull request by daPhipz**
This adds the ability to display the current date and the fuzzy time. See this picture:
current

First off - I'd totally respect it if you said that this is intended to be a very simple , KISS-style extension that is good the way it is. So if this is too much, just say no ;)

I am a total noob at javascript, so please take a look at the code and do not hesitate to make harsh changes - I am happy to learn!

### What I did:
In **`_fuzzyDateTemplate`**, I construct the date part of the displayed string. The weekday abbreviations are stored in `dayNames` (according to the [`Date.getDay()` documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay), 0 represents Sunday - therefore, `'Sun'` is the first element).

In **`toString`**, I combine the date and time strings into one. I find that two spaces around the dash make a good spacer, but I don't know how this looks on bigger or smaller screens - I only have one laptop... Are you able to test this with different screen sizes?

### What could be done in the future:

- **Add localization**
  This is a big thing: As first step, we could simply translate the strings. If you approve this idea, I'd be happy to propose a PR!
  A step further would be implementing the English way of writing dates (`Nov 1st`, `2nd`, `3rd`, `4th` etc) and keep the current variant for other languages. Are there other things to watch out for in other languages?
- **Make displaying the date optional**
  Big thing as well, we would have to make a whole settings menu first.
- **More ideas? Drop 'em here :wink:**

### CODE REVIEW

**Comment by daPhipz** [comment]
I just noticed that it breaks the tests - will fix it rn!

**Comment by daPhipz** [comment]
Please decide on #11 first, so I can implement the changes here.

**Comment by dallagi** [comment]
Hi @daPhipz , I appreciate the work you're doing, but I'm not sure this is the right approach to support weekdate and day.
Formatting and localizing the day/date goes beyond the responsibility of this extension: it would make things more complex, and I'm afraid it would also bring some other problems e.g., it would break the related settings in the gnome tweaks tool.

Perhaps a better approach would be to read the value of the label before overwriting it, so that this extension could replace only the time string and leave the rest unaltered? This way we wouldn't have to think about user settings, localization of dates etc.

What do you think?

**Comment by daPhipz** [comment]
Thanks for your reply, @dallagi! I have absolutely no problem with that ;)
As a matter of fact, your Idea with reading the "original" date value is 100% better than my approach.
Since I have quite a lot to do at the moment though, it might take some time until I can have a shot at this. I will close this PR and open a new one when I have the time.

**Pull request closed without merging**
