### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by daPhipz**

### CODE REVIEW

**Comment by dallagi** [comment]
Thanks a lot for your contribution!
I'd like to ask you a small modification before I merge this: could you please downcase the translated strings?

This made me realize that the German translations are capitalized as well, which is inconsistent with the other languages and I will fix it as soon as I can.

Thanks!

**Comment by daPhipz** [comment]
There you go :)

**Comment by daPhipz** [comment]
About changing the German translation to lowercase - I am German and not everything should be lowercase. The Numbers yes, but the other stuff (Ten to x, half past x) should be uppercase. I am about to open a PR with the changes ;)

**Comment by daPhipz** [comment]
#4

**Comment by dallagi** [comment]
Thanks a lot! Merging now :)

**Pull request merged**
